import test from "node:test";import assert from "node:assert/strict";
import {createSeasonPlan,agriculturalCalendar,createRainfall,climateSnapshot,createSupplier,createPurchaseOrder,supplierPriceHistory,futureInputRequirements,createStorageLot,createSale,createDelivery,compareSeasons,compareFields,indicators,managementReport,exportTable,globalAgriculturalSearch,intelligentAlerts,fieldMobileSnapshot} from "../src/commercial-p1.js";

test("P28-32 planejamento calendário meta chuva e clima offline",()=>{const p=createSeasonPlan({seasonId:"s1",name:"Soja 26/27",startsAt:"2026-10-01",endsAt:"2027-03-01",expectedYieldPerHa:60});const rain=createRainfall({fieldId:"f1",mm:32,measuredAt:"2026-10-02"});assert.equal(p.expectedYieldPerHa,60);assert.equal(agriculturalCalendar({plans:[p],rainfall:[rain]}).length,2);assert.equal(climateSnapshot({rainfall:[rain]}).totalRainMm,32);assert.equal(climateSnapshot({rainfall:[rain]}).mode,"offline-local");});
test("P33-35 compras fornecedores preços e necessidade futura",()=>{const s=createSupplier({name:"Coop"});const o=createPurchaseOrder({supplierId:s.id,seasonId:"s1",items:[{inputId:"seed",quantity:10,unitCostMinor:5000}]});assert.equal(o.totalMinor,50000);assert.equal(supplierPriceHistory([o])[`${s.id}:seed`][0].unitCostMinor,5000);const req=futureInputRequirements({plannedOperations:[{inputs:[{inputId:"seed",quantity:20}]}],stock:[{sku:"seed",available:5}]});assert.equal(req[0].toBuy,15);});
test("P36-38 armazenagem comercialização contratos e entregas",()=>{const lot=createStorageLot({seasonId:"s1",warehouse:"Silo 1",quantity:100,unit:"t"});const sale=createSale({seasonId:"s1",buyer:"Cooperativa",quantity:30,unit:"t",unitPriceMinor:150000,storageLotId:lot.id});const delivery=createDelivery({saleId:sale.id,quantity:10});assert.equal(lot.status,"available");assert.equal(sale.status,"contracted");assert.equal(delivery.status,"delivered");});
test("P39-43 comparativos indicadores relatórios e exportações",()=>{const data={fields:[{id:"f1",name:"T1",areaHa:10}],seasons:[{id:"s1",name:"Soja"}],harvest:[{seasonId:"s1",fieldId:"f1",quantity:600,areaHa:10}],finance:[{direction:"expense",amountMinor:100000,metadata:{seasonId:"s1",fieldId:"f1"}},{direction:"income",amountMinor:300000,metadata:{seasonId:"s1",fieldId:"f1"}}]};assert.equal(compareSeasons(data)[0].marginMinor,200000);assert.equal(compareFields(data)[0].costPerHaMinor,10000);assert.equal(indicators(data).marginMinor,200000);assert.equal(managementReport(data).fieldComparison.length,1);assert.match(exportTable({rows:[{a:1}]}),/"a"/);assert.equal(exportTable({format:"xlsx-model",rows:[{a:1}]}).sheet,"Gestão agrícola");});
test("P44-46 busca alertas e campo mobile offline",()=>{assert.equal(globalAgriculturalSearch({query:"soja",collections:{seasons:[{id:"s1",name:"Soja 26/27"}]}}).length,1);assert.equal(intelligentAlerts({requirements:[{inputId:"seed",toBuy:5}],rainfall:[]}).length,2);const m=fieldMobileSnapshot({operations:[{id:"o1",status:"planned"}],scouting:[],rainfall:[]});assert.equal(m.offlineReady,true);assert.equal(m.pendingOperations.length,1);});
test("P47 valida dados comerciais inválidos",()=>{assert.throws(()=>createPurchaseOrder({supplierId:"s1",items:[]}));assert.throws(()=>createStorageLot({seasonId:"s1",warehouse:"S",quantity:0,unit:"t"}));assert.throws(()=>createSale({seasonId:"s1",buyer:"",quantity:1,unit:"t"}));});
