import test from 'node:test';import assert from 'node:assert/strict';
import {createApplicationRecord,createScoutingRecord,createFieldGeometry,inventoryPhysicalCount,inventoryTransfer,createHarvestRecord,budgetVsActual,seasonResults,managementSnapshot} from '../src/commercial-p0.js';

test('P18 aplicação calcula quantidade por dose/ha e preserva contexto agronômico',()=>{const x=createApplicationRecord({seasonId:'s1',fieldId:'f1',areaHa:50,target:'lagarta',temperatureC:24,humidityPct:65,windKmh:8,products:[{inputId:'i1',name:'Produto A',unit:'L',dosePerHa:2}]});assert.equal(x.products[0].quantity,100);assert.equal(x.target,'lagarta');assert.equal(x.weather.windKmh,8);});
test('P19 monitoramento registra praga/doença/erva com severidade e localização',()=>{const x=createScoutingRecord({seasonId:'s1',fieldId:'f1',kind:'praga',name:'Lagarta',severity:4,affectedAreaHa:2,latitude:-21.1,longitude:-47.8});assert.equal(x.severity,4);assert.equal(x.status,'open');});
test('P20 GIS exige polígono válido e mantém coordenadas localmente',()=>{const x=createFieldGeometry({fieldId:'f1',coordinates:[[-47.8,-21.1],[-47.7,-21.1],[-47.7,-21.2]]});assert.equal(x.type,'Polygon');assert.equal(x.coordinates.length,3);assert.throws(()=>createFieldGeometry({fieldId:'f1',coordinates:[[1,2]]}));});
test('P21 estoque 2.0 suporta contagem física e transferência entre armazéns',()=>{const c=inventoryPhysicalCount({sku:'i1',systemQuantity:100,countedQuantity:96});assert.equal(c.adjustmentQuantity,-4);const t=inventoryTransfer({sku:'i1',quantity:20,fromWarehouse:'A',toWarehouse:'B'});assert.equal(t.quantity,20);assert.throws(()=>inventoryTransfer({sku:'i1',quantity:1,fromWarehouse:'A',toWarehouse:'A'}));});
test('P22 colheita 2.0 calcula produtividade e registra qualidade/destino',()=>{const h=createHarvestRecord({seasonId:'s1',fieldId:'f1',quantity:3000,unit:'kg',areaHa:2,moisturePct:13,impurityPct:1.2,lossPct:0.5,destination:'Silo 1'});assert.equal(h.yieldPerHa,1500);assert.equal(h.moisturePct,13);assert.equal(h.destination,'Silo 1');});
test('P23-25 financeiro agrícola consolida orçado, realizado e resultado da safra',()=>{const seasons=[{id:'s1',budgetMinor:1000000}],entries=[{direction:'expense',amountMinor:400000,metadata:{seasonId:'s1'}},{direction:'income',amountMinor:900000,metadata:{seasonId:'s1'}}],harvestLots=[{seasonId:'s1',quantity:100,areaHa:10}];const b=budgetVsActual({seasons,entries});assert.equal(b.s1.varianceMinor,600000);assert.equal(b.s1.usedPct,40);const r=seasonResults({seasons,entries,harvestLots});assert.equal(r.s1.marginMinor,500000);assert.equal(r.s1.yieldPerHa,10);});
test('P26 dashboard gerencial agrega operação, área, monitoramento e financeiro',()=>{const x=managementSnapshot({fields:[{areaHa:10},{areaHa:20}],seasons:[{id:'s1'}],operations:[{status:'planned'},{status:'completed'}],scouting:[{status:'open'}],entries:[{direction:'expense',amountMinor:100},{direction:'income',amountMinor:250}]});assert.equal(x.totalAreaHa,30);assert.equal(x.openOperations,1);assert.equal(x.openScouting,1);assert.equal(x.totalIncomeMinor,250);});
test('P27 validações comerciais rejeitam dados que quebrariam rastreabilidade',()=>{assert.throws(()=>createApplicationRecord({seasonId:'s',fieldId:'f',areaHa:10,products:[]}));assert.throws(()=>createHarvestRecord({seasonId:'s',fieldId:'f',quantity:0,unit:'kg',areaHa:1}));});
