import React,{useState} from 'react';
import {PageHeader} from './primitives.jsx';
import {parseGisFile} from './gis-file-parser.js';
import './gis-import.css';

const geoTypes=summary=>Object.entries(summary?.geometryTypes??{}).map(([type,count])=>`${type}: ${count}`).join(' · ')||'—';

export function LavouraGisImport({data,onRun}){
  const [parsed,setParsed]=useState(null);const [name,setName]=useState('');const [selectedLayer,setSelectedLayer]=useState(null);const [featureIndex,setFeatureIndex]=useState('0');const [fieldId,setFieldId]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const layers=data?.layers??[],fields=data?.fields??[];
  async function analyze(file){if(!file)return;setError('');setBusy(true);try{const bytes=new Uint8Array(await file.arrayBuffer());const textual=/\.(geojson|json|kml|gpx|xml)$/i.test(file.name);const result=await parseGisFile({name:file.name,type:file.type,bytes,text:textual?new TextDecoder().decode(bytes):null});setParsed(result);setName(file.name.replace(/\.[^.]+$/,''));}catch(err){setParsed(null);setError(err.message);}finally{setBusy(false);}}
  async function save(){if(!parsed)return;setBusy(true);setError('');try{await onRun('saveLayer',{layer:{name:name||parsed.sourceFile||'Camada GIS',format:parsed.format,sourceFile:parsed.sourceFile,featureCollection:parsed.featureCollection,warnings:parsed.warnings}});setParsed(null);setName('');}catch(err){setError(err.message);}finally{setBusy(false);}}
  async function apply(){if(!selectedLayer||!fieldId)return;setBusy(true);setError('');try{await onRun('applyFieldGeometry',{layerId:selectedLayer.id,featureIndex:Number(featureIndex),fieldId});}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <section className="product-workspace gis-import-workspace" data-testid="gis-import-workspace">
    <PageHeader eyebrow="Produção" title="Importação GIS" description="Traga mapas do produtor para o Lavoura sem enviar arquivos para serviços externos."/>
    <section className="workspace-panel gis-import-drop"><div><strong>GeoJSON, KML, KMZ, GPX, Shapefile ZIP e ISOXML/TaskData</strong><p>O arquivo é analisado localmente e normalizado para coordenadas WGS84.</p></div><label className="primary-button file-button">{busy?'Analisando…':'Selecionar arquivo'}<input type="file" disabled={busy} accept=".geojson,.json,.kml,.kmz,.gpx,.zip,.xml" onChange={event=>analyze(event.target.files?.[0])}/></label></section>
    {error?<div className="error" role="alert">{error}</div>:null}
    {parsed?<section className="workspace-panel" data-testid="gis-preview"><div className="panel-heading"><div><span className="eyebrow">Prévia local</span><h3>{parsed.sourceFile}</h3></div><span>{parsed.format.toUpperCase()}</span></div><div className="workspace-kpis"><article className="workspace-kpi"><span>Feições</span><strong>{parsed.featureCollection.summary.featureCount}</strong></article><article className="workspace-kpi"><span>Geometrias</span><strong>{Object.keys(parsed.featureCollection.summary.geometryTypes).length}</strong></article></div><p>{geoTypes(parsed.featureCollection.summary)}</p>{parsed.warnings?.length?<ul>{parsed.warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul>:null}<label>Nome da camada<input value={name} onChange={event=>setName(event.target.value)}/></label><button type="button" onClick={save} disabled={busy}>Salvar camada</button></section>:null}
    <section className="workspace-panel"><div className="panel-heading"><div><span className="eyebrow">Camadas locais</span><h3>Dados GIS importados</h3></div><span>{layers.length}</span></div>{layers.length?<div className="gis-layer-list">{layers.map(layer=><article key={layer.id} className={selectedLayer?.id===layer.id?'gis-layer-card selected':'gis-layer-card'} onClick={()=>{setSelectedLayer(layer);setFeatureIndex('0');}}><div><strong>{layer.name}</strong><small>{layer.format?.toUpperCase()} · {layer.summary?.featureCount??0} feições · {geoTypes(layer.summary)}</small></div><button type="button" className="danger-ghost" onClick={async event=>{event.stopPropagation();await onRun('removeLayer',{id:layer.id});if(selectedLayer?.id===layer.id)setSelectedLayer(null);}}>Excluir</button></article>)}</div>:<p className="muted">Nenhuma camada GIS importada.</p>}</section>
    {selectedLayer?<section className="workspace-panel"><div className="panel-heading"><div><span className="eyebrow">Limite do talhão</span><h3>Aplicar feição poligonal</h3></div></div><div className="gis-apply-grid"><label>Feição<select value={featureIndex} onChange={event=>setFeatureIndex(event.target.value)}>{selectedLayer.featureCollection.features.map((feature,index)=><option key={index} value={index}>{index+1} · {feature.properties?.name??feature.geometry.type}</option>)}</select></label><label>Talhão<select value={fieldId} onChange={event=>setFieldId(event.target.value)}><option value="">Selecione</option>{fields.map(field=><option key={field.id} value={field.id}>{field.code?`${field.code} · `:''}{field.name}</option>)}</select></label><button type="button" onClick={apply} disabled={!fieldId||busy}>Aplicar ao talhão</button></div><p className="muted">A camada original permanece salva mesmo depois de aplicada ao talhão.</p></section>:null}
  </section>;
}
