import React,{useMemo,useState} from 'react';
import {getUiContract,hydrateUiFields,referenceLabel} from './contracts.js';
import {DataTable,KpiStrip,Modal,PageHeader,StructuredForm,recordRows} from './primitives.jsx';

export function LavouraHarvestWorkspace({data,onRun}){
 const contract=getUiContract('harvest'),refs=data?.references??{},commercial=data?.commercial??{},rows=useMemo(()=>recordRows(data),[data]);
 const [actionName,setActionName]=useState(null),[busy,setBusy]=useState(false);const action=actionName?contract.actions[actionName]:null,fields=useMemo(()=>hydrateUiFields(action?.fields??[],refs),[action,refs]);
 const columns=[{key:'harvestedAt',label:'Data',render:r=>r.harvestedAt?new Date(r.harvestedAt).toLocaleDateString('pt-BR'):'—'},{key:'fieldId',label:'Talhão',render:r=>referenceLabel(refs,'fieldOptions',r.fieldId)},{key:'quantity',label:'Produção',render:r=>`${Number(r.quantity||0).toLocaleString('pt-BR')} ${r.unit||''}`},{key:'yieldPerHa',label:'Produtividade/ha',render:r=>Number(r.yieldPerHa||0).toLocaleString('pt-BR')},{key:'destination',label:'Destino'}];
 async function submit(v){setBusy(true);try{await onRun(actionName,v);setActionName(null);}finally{setBusy(false)}}
 const storage=commercial.storageLots??[];return <section className="product-workspace" data-testid="harvest-workspace"><PageHeader eyebrow="Produção" title="Colheita e armazenagem" description="Da colheita ao silo: produtividade, qualidade, romaneio e estoque de produção." actions={<><button className="primary-button" onClick={()=>setActionName('create')}>Registrar colheita</button><button onClick={()=>setActionName('addStorage')}>Lote armazenado</button></>}/><KpiStrip items={[{label:'Registros de colheita',value:rows.length},{label:'Lotes armazenados',value:storage.length},{label:'Quantidade armazenada',value:storage.reduce((s,x)=>s+Number(x.availableQuantity??x.quantity??0),0).toLocaleString('pt-BR')}]}/><DataTable columns={columns} rows={rows} emptyTitle="Nenhuma colheita registrada"/><section className="workspace-panel"><div className="panel-heading"><div><span className="eyebrow">Armazenagem</span><h3>Silos e lotes de produção</h3></div></div><div className="checklist-stack">{storage.map(x=><article className="checklist-card" key={x.id}><strong>{x.warehouse}</strong><small>{Number(x.availableQuantity??x.quantity).toLocaleString('pt-BR')} {x.unit} · {referenceLabel(refs,'seasonOptions',x.seasonId)} · {x.status}</small></article>)}</div></section><Modal open={Boolean(action)} title={action?.label??'Registro'} onClose={()=>setActionName(null)}><StructuredForm fields={fields} busy={busy} submitLabel={action?.label} onSubmit={submit} onCancel={()=>setActionName(null)}/></Modal></section>;
}
