import React,{useMemo,useState} from 'react';
import {PageHeader} from './primitives.jsx';
import {AgriculturalMapPanel} from './agricultural-map.jsx';
import {ndviFromGeoTiffs,ndviToDataUrl} from './satellite-raster.js';
import './satellite.css';

const today=()=>new Date().toISOString().slice(0,10);
const monthAgo=()=>new Date(Date.now()-30*86400000).toISOString().slice(0,10);
function geometryBounds(record){const value=record?.geometry??record;const coordinates=value?.coordinates;if(!coordinates)return null;const flat=[];const walk=node=>{if(Array.isArray(node)&&node.length>=2&&Number.isFinite(Number(node[0]))&&Number.isFinite(Number(node[1]))){flat.push([Number(node[0]),Number(node[1])]);return;}if(Array.isArray(node))node.forEach(walk);};walk(coordinates);if(!flat.length)return null;return{minLongitude:Math.min(...flat.map(p=>p[0])),minLatitude:Math.min(...flat.map(p=>p[1])),maxLongitude:Math.max(...flat.map(p=>p[0])),maxLatitude:Math.max(...flat.map(p=>p[1]))};}
async function previewDataUrl(url){if(!url)return null;const response=await fetch(url);if(!response.ok)throw new Error(`Preview indisponível (${response.status}).`);const blob=await response.blob();if(blob.size>8*1024*1024)throw new Error('Preview excede 8 MiB.');return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob);});}

export function LavouraSatellite({data,onRun}){
  const [provider,setProvider]=useState('sentinel2');const [fieldId,setFieldId]=useState('');const [from,setFrom]=useState(monthAgo);const [to,setTo]=useState(today);const [maxCloud,setMaxCloud]=useState(30);const [results,setResults]=useState([]);const [selected,setSelected]=useState(null);const [mode,setMode]=useState('vector');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [redFile,setRedFile]=useState(null);const [nirFile,setNirFile]=useState(null);
  const fields=data?.fields??[],geometries=data?.geometries??[],cached=data?.cached??[];
  const selectedField=fields.find(field=>String(field.id)===String(fieldId));
  const selectedGeometry=geometries.find(item=>String(item.fieldId??item.id)===String(fieldId));
  const selectedCached=selected?cached.find(item=>item.id===`${selected.provider}:${selected.id}`)??cached.find(item=>item.scene?.id===selected.id):null;
  const imagery=selectedCached?.previewDataUrl??selected?.assets?.preview??null;
  const ndviImage=useMemo(()=>selectedCached?.ndvi?ndviToDataUrl(selectedCached.ndvi):null,[selectedCached]);
  async function search(){const bounds=geometryBounds(selectedGeometry);if(!selectedField||!bounds){setError('Selecione um talhão com polígono mapeado.');return;}setBusy(true);setError('');try{const found=await onRun('searchScenes',{provider,bounds,from,to,maxCloud:Number(maxCloud),limit:12});setResults(found??[]);if(found?.[0])setSelected(found[0]);}catch(err){setError(err.message);}finally{setBusy(false);}}
  async function cache(scene){setBusy(true);setError('');try{let preview=null;try{preview=await previewDataUrl(scene.assets?.preview);}catch{}await onRun('cacheScene',{scene,previewDataUrl:preview});setSelected(scene);}catch(err){setError(err.message);}finally{setBusy(false);}}
  async function calculate(){if(!selectedCached||!redFile||!nirFile)return;setBusy(true);setError('');try{const ndvi=await ndviFromGeoTiffs({redSource:redFile,nirSource:nirFile,targetWidth:256,targetHeight:256});await onRun('saveNdvi',{id:selectedCached.id,ndvi});setMode('ndvi');}catch(err){setError(err.message);}finally{setBusy(false);}}
  return <section className="product-workspace satellite-workspace" data-testid="satellite-workspace">
    <PageHeader eyebrow="Monitoramento" title="Satélite" description="Consulte catálogos oficiais e mantenha previews/NDVI localmente. Internet é opcional para o produto."/>
    <section className="workspace-panel satellite-controls"><label>Talhão<select value={fieldId} onChange={event=>setFieldId(event.target.value)}><option value="">Selecione</option>{fields.map(field=><option key={field.id} value={field.id}>{field.code?`${field.code} · `:''}{field.name}</option>)}</select></label><label>Fonte<select value={provider} onChange={event=>setProvider(event.target.value)}>{Object.values(data?.providers??{}).map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>De<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>Até<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><label>Nuvens máx. %<input type="number" min="0" max="100" value={maxCloud} onChange={event=>setMaxCloud(event.target.value)}/></label><button type="button" onClick={search} disabled={busy}>Buscar imagens</button></section>
    {error?<div className="error" role="alert">{error}</div>:null}
    <div className="satellite-mode-tabs" role="tablist"><button className={mode==='vector'?'active':''} onClick={()=>setMode('vector')}>Vetorial</button><button className={mode==='imagery'?'active':''} onClick={()=>setMode('imagery')}>Imagem</button><button className={mode==='ndvi'?'active':''} onClick={()=>setMode('ndvi')}>NDVI</button></div>
    {mode==='vector'?<AgriculturalMapPanel map={data?.map}/>:mode==='imagery'?<section className="satellite-view">{imagery?<img src={imagery} alt="Preview da cena de satélite selecionada"/>:<div className="map-empty"><strong>Sem preview</strong><span>Selecione uma cena com preview ou use o modo vetorial.</span></div>}</section>:<section className="satellite-view">{ndviImage?<img className="ndvi-image" src={ndviImage} alt="NDVI local da cena selecionada"/>:<div className="map-empty"><strong>NDVI ainda não calculado</strong><span>Salve a cena offline e selecione as bandas vermelha e NIR.</span></div>}</section>}
    <section className="workspace-panel"><div className="panel-heading"><div><span className="eyebrow">Resultados online</span><h3>Cenas encontradas</h3></div><span>{results.length}</span></div>{results.length?<div className="satellite-scenes">{results.map(scene=><article key={`${scene.provider}:${scene.id}`} className={selected?.id===scene.id?'satellite-card selected':'satellite-card'} onClick={()=>setSelected(scene)}>{scene.assets.preview?<img src={scene.assets.preview} alt="" loading="lazy"/>:<div className="satellite-placeholder">Sem preview</div>}<div><strong>{new Date(scene.observedAt).toLocaleDateString('pt-BR')}</strong><span>{scene.providerLabel}</span><small>Nuvens: {scene.cloudCover==null?'—':`${scene.cloudCover}%`}</small></div><button type="button" onClick={event=>{event.stopPropagation();void cache(scene);}}>Salvar offline</button></article>)}</div>:<p className="muted">A busca é opcional. O cache local continua disponível sem internet.</p>}</section>
    <section className="workspace-panel"><div className="panel-heading"><div><span className="eyebrow">Cache local</span><h3>Cenas salvas</h3></div><span>{cached.length}</span></div>{cached.length?<div className="satellite-cache-list">{cached.map(item=><article key={item.id}><button type="button" onClick={()=>{setSelected(item.scene);setMode(item.ndvi?'ndvi':'imagery');}}><strong>{item.scene.id}</strong><span>{new Date(item.scene.observedAt).toLocaleDateString('pt-BR')}</span></button><button type="button" className="danger-ghost" onClick={()=>onRun('removeCachedScene',{id:item.id})}>Remover</button></article>)}</div>:<p className="muted">Nenhuma cena salva offline.</p>}</section>
    {selectedCached?<section className="workspace-panel"><div className="panel-heading"><div><span className="eyebrow">NDVI local</span><h3>Processar bandas GeoTIFF</h3></div>{selectedCached.ndvi?.summary?<span>Média {Number(selectedCached.ndvi.summary.mean).toFixed(2)}</span>:null}</div><div className="ndvi-inputs"><label>Vermelho<input type="file" accept=".tif,.tiff" onChange={event=>setRedFile(event.target.files?.[0]??null)}/></label><label>NIR<input type="file" accept=".tif,.tiff" onChange={event=>setNirFile(event.target.files?.[0]??null)}/></label><button type="button" disabled={!redFile||!nirFile||busy} onClick={calculate}>Calcular NDVI</button></div><p className="muted">O cálculo é feito no dispositivo. Nenhum raster é enviado à ArtiSys.</p></section>:null}
  </section>;
}
