import { createHash } from 'node:crypto';
import { readFile, readdir } from 'node:fs/promises';
import { join } from 'node:path';
import { SqliteStorage } from '../../../vendor/release-modules/artisys-storage/src/index.mjs';

const text = (value, label) => {if (typeof value !== 'string' || value.trim() === '') throw new TypeError(`${label} is required.`);return value.trim();};
const json = (value, label = 'value') => {try {const encoded = JSON.stringify(value);if (encoded === undefined) throw new TypeError(`${label} must be JSON-serializable.`);return encoded;} catch (error) {if (error instanceof TypeError && error.message.endsWith('must be JSON-serializable.')) throw error;throw new TypeError(`${label} must be JSON-serializable.`);}};
const checksum = (value) => createHash('sha256').update(value).digest('hex');
const now = () => new Date().toISOString();
const COMMON_SCHEMA = `
CREATE TABLE IF NOT EXISTS __artisys_meta (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS __artisys_migrations (id TEXT PRIMARY KEY, checksum TEXT NOT NULL, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS __artisys_seeds (id TEXT PRIMARY KEY, checksum TEXT NOT NULL, applied_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS __artisys_records (collection TEXT NOT NULL, id TEXT NOT NULL, payload_json TEXT NOT NULL,version INTEGER NOT NULL CHECK(version > 0), created_at TEXT NOT NULL,updated_at TEXT NOT NULL, deleted_at TEXT, PRIMARY KEY(collection, id));
CREATE TABLE IF NOT EXISTS __artisys_record_history (sequence INTEGER PRIMARY KEY AUTOINCREMENT, collection TEXT NOT NULL, id TEXT NOT NULL,operation TEXT NOT NULL CHECK(operation IN ('create','update','delete')),version INTEGER NOT NULL CHECK(version > 0), payload_json TEXT NOT NULL, occurred_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS __artisys_records_collection_idx ON __artisys_records(collection, deleted_at, id);
CREATE INDEX IF NOT EXISTS __artisys_history_record_idx ON __artisys_record_history(collection, id, sequence);
`;
async function transaction(db, work) {await db.exec('BEGIN IMMEDIATE;');try {const result = await work();await db.exec('COMMIT;');return result;} catch (error) {try { await db.exec('ROLLBACK;'); } catch {}throw error;}}
function rowToRecord(row) {if (!row) return null;return {collection: row.collection,id: row.id,payload: JSON.parse(row.payload_json),version: Number(row.version),createdAt: row.created_at,updatedAt: row.updated_at,deletedAt: row.deleted_at ?? null};}
export async function loadSqlMigrations(sources = []) {const migrations = [];for (const source of sources) {const namespace = text(source?.namespace, 'Migration namespace');const dir = text(source?.dir, 'Migration directory');const entries = (await readdir(dir, { withFileTypes: true })).filter((entry) => entry.isFile() && entry.name.endsWith('.sql')).map((entry) => entry.name).sort();for (const filename of entries) migrations.push({ id: `${namespace}/${filename}`, sql: await readFile(join(dir, filename), 'utf8') });}return migrations.sort((a, b) => a.id.localeCompare(b.id));}
export async function openProductPersistence({ dbPath, productId, migrations = [], storageFactory = (filePath) => new SqliteStorage({ filePath }) } = {}) {
  const id = text(productId, 'Product id');const path = text(dbPath, 'Database path');const db = await storageFactory(path);
  if (!db || typeof db.exec !== 'function' || typeof db.run !== 'function' || typeof db.getRow !== 'function' || typeof db.allRows !== 'function') throw new TypeError('Storage adapter must expose SQLite exec/run/getRow/allRows primitives.');
  try {await db.exec(COMMON_SCHEMA);const productRow = await db.getRow("SELECT value FROM __artisys_meta WHERE key='product_id'");if (productRow && productRow.value !== id) throw new Error(`Database belongs to product ${productRow.value}, not ${id}.`);if (!productRow) await db.run("INSERT INTO __artisys_meta(key,value) VALUES('product_id',?)", [id]);for (const migration of [...migrations].sort((a, b) => a.id.localeCompare(b.id))) {const migrationId = text(migration?.id, 'Migration id');const sql = text(migration?.sql, 'Migration SQL');const digest = checksum(sql);const applied = await db.getRow('SELECT checksum FROM __artisys_migrations WHERE id=?', [migrationId]);if (applied) {if (applied.checksum !== digest) throw new Error(`Migration checksum mismatch for ${migrationId}.`);continue;}await transaction(db, async () => {const race = await db.getRow('SELECT checksum FROM __artisys_migrations WHERE id=?', [migrationId]);if (race) {if (race.checksum !== digest) throw new Error(`Migration checksum mismatch for ${migrationId}.`);return;}await db.exec(sql);await db.run('INSERT INTO __artisys_migrations(id,checksum,applied_at) VALUES(?,?,?)', [migrationId, digest, now()]);});}} catch (error) {await db.close?.();throw error;}
  return Object.freeze({
    async applySeed({ id: seedId, value } = {}) {const normalizedId = text(seedId, 'Seed id');const payloadJson = json(value, 'Seed value');const digest = checksum(payloadJson);const existing = await db.getRow('SELECT checksum FROM __artisys_seeds WHERE id=?', [normalizedId]);if (existing) {if (existing.checksum !== digest) throw new Error(`Seed checksum mismatch for ${normalizedId}.`);return { applied: false, id: normalizedId };}return transaction(db, async () => {const race = await db.getRow('SELECT checksum FROM __artisys_seeds WHERE id=?', [normalizedId]);if (race) {if (race.checksum !== digest) throw new Error(`Seed checksum mismatch for ${normalizedId}.`);return { applied: false, id: normalizedId };}const timestamp = now();await db.run("INSERT INTO __artisys_records(collection,id,payload_json,version,created_at,updated_at,deleted_at) VALUES('__seed__',?,?,1,?,?,NULL)", [normalizedId, payloadJson, timestamp, timestamp]);await db.run("INSERT INTO __artisys_record_history(collection,id,operation,version,payload_json,occurred_at) VALUES('__seed__',?,'create',1,?,?)", [normalizedId, payloadJson, timestamp]);await db.run('INSERT INTO __artisys_seeds(id,checksum,applied_at) VALUES(?,?,?)', [normalizedId, digest, timestamp]);return { applied: true, id: normalizedId };});},
    async putRecord(collection, recordId, payload, { expectedVersion } = {}) {const normalizedCollection = text(collection, 'Collection');const normalizedId = text(recordId, 'Record id');const payloadJson = json(payload, 'Record payload');return transaction(db, async () => {const current = await db.getRow('SELECT * FROM __artisys_records WHERE collection=? AND id=?', [normalizedCollection, normalizedId]);const currentVersion = current ? Number(current.version) : 0;if (expectedVersion !== undefined && expectedVersion !== currentVersion) throw new Error(`Version conflict for ${normalizedCollection}/${normalizedId}: expected ${expectedVersion}, current ${currentVersion}.`);if (current?.deleted_at) throw new Error(`Record ${normalizedCollection}/${normalizedId} is deleted.`);const timestamp = now();const version = currentVersion + 1;const operation = current ? 'update' : 'create';if (current) await db.run('UPDATE __artisys_records SET payload_json=?,version=?,updated_at=? WHERE collection=? AND id=?', [payloadJson, version, timestamp, normalizedCollection, normalizedId]);else await db.run('INSERT INTO __artisys_records(collection,id,payload_json,version,created_at,updated_at,deleted_at) VALUES(?,?,?,?,?,?,NULL)', [normalizedCollection, normalizedId, payloadJson, version, timestamp, timestamp]);await db.run('INSERT INTO __artisys_record_history(collection,id,operation,version,payload_json,occurred_at) VALUES(?,?,?,?,?,?)', [normalizedCollection, normalizedId, operation, version, payloadJson, timestamp]);return rowToRecord(await db.getRow('SELECT * FROM __artisys_records WHERE collection=? AND id=?', [normalizedCollection, normalizedId]));});},
    async getRecord(collection, recordId, { includeDeleted = false } = {}) {const normalizedCollection = text(collection, 'Collection');const normalizedId = text(recordId, 'Record id');const row = await db.getRow('SELECT * FROM __artisys_records WHERE collection=? AND id=?', [normalizedCollection, normalizedId]);if (!row || (!includeDeleted && row.deleted_at)) return null;return rowToRecord(row);},
    async listRecords(collection, { includeDeleted = false } = {}) {const normalizedCollection = text(collection, 'Collection');const sql = includeDeleted ? 'SELECT * FROM __artisys_records WHERE collection=? ORDER BY id' : 'SELECT * FROM __artisys_records WHERE collection=? AND deleted_at IS NULL ORDER BY id';return (await db.allRows(sql, [normalizedCollection])).map(rowToRecord);},
    async listCollections({ includeSystem = false, includeEmpty = false } = {}) {const where = includeEmpty ? '' : ' WHERE deleted_at IS NULL';const rows = await db.allRows(`SELECT DISTINCT collection FROM __artisys_records${where} ORDER BY collection`);return rows.map((row) => row.collection).filter((collection) => includeSystem || !collection.startsWith('__'));},
    async softDeleteRecord(collection, recordId, { expectedVersion } = {}) {const normalizedCollection = text(collection, 'Collection');const normalizedId = text(recordId, 'Record id');return transaction(db, async () => {const current = await db.getRow('SELECT * FROM __artisys_records WHERE collection=? AND id=?', [normalizedCollection, normalizedId]);if (!current || current.deleted_at) throw new Error(`Active record not found: ${normalizedCollection}/${normalizedId}.`);const currentVersion = Number(current.version);if (expectedVersion !== undefined && expectedVersion !== currentVersion) throw new Error(`Version conflict for ${normalizedCollection}/${normalizedId}: expected ${expectedVersion}, current ${currentVersion}.`);const timestamp = now();const version = currentVersion + 1;await db.run('UPDATE __artisys_records SET version=?,updated_at=?,deleted_at=? WHERE collection=? AND id=?', [version, timestamp, timestamp, normalizedCollection, normalizedId]);await db.run("INSERT INTO __artisys_record_history(collection,id,operation,version,payload_json,occurred_at) VALUES(?,?,'delete',?,?,?)", [normalizedCollection, normalizedId, version, current.payload_json, timestamp]);return rowToRecord(await db.getRow('SELECT * FROM __artisys_records WHERE collection=? AND id=?', [normalizedCollection, normalizedId]));});},
    async recordHistory(collection, recordId) {const normalizedCollection = text(collection, 'Collection');const normalizedId = text(recordId, 'Record id');return (await db.allRows('SELECT sequence,operation,version,payload_json,occurred_at FROM __artisys_record_history WHERE collection=? AND id=? ORDER BY sequence', [normalizedCollection, normalizedId])).map((row) => ({ sequence: Number(row.sequence), operation: row.operation, version: Number(row.version), payload: JSON.parse(row.payload_json), occurredAt: row.occurred_at }));},
    async schemaState() {const rows = await db.allRows('SELECT id,checksum,applied_at FROM __artisys_migrations ORDER BY id');return { productId: id, migrations: rows.map((row) => row.id), migrationDetails: rows.map((row) => ({ id: row.id, checksum: row.checksum, appliedAt: row.applied_at })) };},
    async health() {const storage = await db.health?.();return { ok: storage?.ok !== false, productId: id, storage: storage ?? { ok: true } };},
    close: () => db.close?.()
  });
}