import { nicheUxForScreen } from './niche-ux.js';

const text=(v,l)=>{if(typeof v!=='string'||!v.trim())throw new TypeError(`${l} is required.`);return v.trim();};
const qaCoverage=(event)=>{try{globalThis.__ARTISYS_QA_COVERAGE__?.(event);}catch{}};
const PT_LABELS=Object.freeze({save:'Salvar',create:'Criar',add:'Adicionar',register:'Registrar',update:'Atualizar',edit:'Editar',remove:'Excluir',delete:'Excluir',cancel:'Cancelar',start:'Iniciar',complete:'Concluir',finish:'Finalizar',close:'Encerrar',confirm:'Confirmar',approve:'Aprovar',reject:'Rejeitar',dispatch:'Despachar',receive:'Receber',return:'Devolver',transfer:'Transferir',reserve:'Reservar',release:'Liberar',assign:'Atribuir',unassign:'Remover vínculo',acknowledge:'Reconhecer',dismiss:'Dispensar',snooze:'Adiar',restore:'Restaurar',restoreByCode:'Restaurar por código',recoveryCode:'Gerar código de recuperação',backup:'Criar backup',submit:'Enviar',reopen:'Reabrir',record:'Registrar',issue:'Emitir'});
const FIELD_LABELS=Object.freeze({id:'ID',code:'Código de recuperação',name:'Nome',title:'Título',description:'Descrição',status:'Status',type:'Tipo',date:'Data',dueAt:'Vencimento',occurredAt:'Data da ocorrência',recordedAt:'Data do registro',expectedVersion:'Versão esperada',assetId:'Ativo',vehicleId:'Veículo',machineId:'Máquina',equipmentId:'Equipamento',workerId:'Colaborador',employeeId:'Colaborador',animalId:'Animal',lotId:'Lote',fieldId:'Talhão',farmUnitId:'Unidade/Fazenda',supplierId:'Fornecedor',customerId:'Cliente',driverId:'Motorista',operatorId:'Operador',contractId:'Contrato',workOrderId:'Ordem de serviço',requestId:'Solicitação',quoteId:'Cotação',freightId:'Frete',visitId:'Visita',quantity:'Quantidade',amount:'Valor',value:'Valor',cost:'Custo',price:'Preço',notes:'Observações',reason:'Motivo',liters:'Litros',hourMeter:'Horímetro',odometerKm:'Odômetro (km)'});
const humanize=value=>String(value??'').replace(/([a-z0-9])([A-Z])/g,'$1 $2').replaceAll(/[-_]+/g,' ').trim().replace(/^./,m=>m.toUpperCase());
const actionLabel=name=>{const key=String(name??'');if(PT_LABELS[key])return PT_LABELS[key];for(const [prefix,label] of Object.entries(PT_LABELS)){if(key.startsWith(prefix)&&key.length>prefix.length)return `${label} ${humanize(key.slice(prefix.length))}`;}return humanize(key);};
const fieldLabel=name=>FIELD_LABELS[name]??humanize(name);
const fieldType=name=>{const key=String(name).toLowerCase();if(key.includes('date')||key.endsWith('at'))return 'datetime-local';if(/(quantity|amount|value|cost|price|liters|hours|hourmeter|odometer|weight|km|version|count)/.test(key))return 'number';if(/(notes|description|reason|details|comment)/.test(key))return 'textarea';if(/^(is|has|enabled|active)/.test(key))return 'checkbox';return 'text';};
const intentFor=name=>/(remove|delete|cancel|dismiss|reject)/i.test(name)?'danger':/(approve|confirm|complete|finish|close|receive|return)/i.test(name)?'success':'primary';
const inferParamNames=handler=>{if(typeof handler!=='function')return [];const source=Function.prototype.toString.call(handler).trim();const match=source.match(/^(?:async\s*)?(?:\(\s*)?\{([^}]*)\}/)??source.match(/^(?:async\s*)?\(\s*\{([^}]*)\}\s*(?:,|\))/);if(!match)return [];return match[1].split(',').map(part=>part.trim().split(/[=:]/)[0]?.trim()).filter(Boolean).filter(name=>/^[A-Za-z_$][\w$]*$/.test(name));};
const inferDefinition=(name,handler,explicit={})=>{const params=inferParamNames(handler);const fields=(explicit.fields??params.map(field=>({name:field,label:fieldLabel(field),type:fieldType(field),required:!['expectedVersion','notes','reason'].includes(field)}))).map(field=>Object.freeze({...field,label:field.label??fieldLabel(field.name),type:field.type??fieldType(field.name)}));return Object.freeze({name,label:explicit.label??actionLabel(name),description:explicit.description??null,intent:explicit.intent??intentFor(name),confirm:explicit.confirm??(/(remove|delete|cancel|dismiss|reject|restore)/i.test(name)?`Confirmar ${String(explicit.label??actionLabel(name)).toLowerCase()}?`:null),requiresSelection:explicit.requiresSelection??(/(remove|delete|cancel|start|complete|finish|close|approve|reject|dispatch|receive|return|transfer|reopen)/i.test(name)&&fields.some(field=>field.name==='id')),fields:Object.freeze(fields)});};

export function createFunctionalPresentation({shell,screens={},services={}}={}){
  if(!shell?.navigation)throw new TypeError('Shell navigation is required.');
  const entries=new Map();
  for(const item of shell.navigation){
    const screen=screens[item.id];
    if(!screen)throw new Error(`Missing functional screen: ${item.id}.`);
    const mergedActions={...screen.actions};const explicitDefinitions={...screen.actionDefinitions};
    if(screen.kind==='settings'&&services.recovery){
      if(typeof services.recovery.createRecoveryCode==='function'&&!mergedActions.recoveryCode){mergedActions.recoveryCode=({id})=>services.recovery.createRecoveryCode(id);explicitDefinitions.recoveryCode={label:'Gerar código de recuperação',fields:[{name:'id',label:'ID do backup',type:'text',required:true}]};}
      if(typeof services.recovery.restoreByRecoveryCode==='function'&&!mergedActions.restoreByCode){mergedActions.restoreByCode=({code})=>services.recovery.restoreByRecoveryCode(code);explicitDefinitions.restoreByCode={label:'Restaurar por código',confirm:'Confirmar restauração pelo código local?',fields:[{name:'code',label:'Código de recuperação',type:'text',required:true}]};}
    }
    const actions=Object.freeze(mergedActions);const definitions=Object.freeze(Object.fromEntries(Object.entries(actions).map(([name,handler])=>[name,inferDefinition(name,handler,explicitDefinitions[name]??{})])));const ux=screen.ux??nicheUxForScreen(shell,item.id);
    entries.set(item.id,Object.freeze({id:item.id,title:screen.title??item.label,kind:screen.kind??'workspace',load:screen.load??(async()=>({})),actions,actionDefinitions:definitions,ux:ux?Object.freeze({...ux}):null}));
  }
  return Object.freeze({shell,services:Object.freeze({...services}),screenIds:()=>Object.freeze([...entries.keys()]),screen(id){const key=text(id,'Screen id'),screen=entries.get(key);if(!screen)throw new Error(`Unknown screen: ${key}.`);return screen;},async load(id,context){const screen=this.screen(id);const result=await screen.load(context);qaCoverage({type:'load-pass',productId:services.security?.productId??null,brand:shell.brand?.name??null,screenId:screen.id});return result;},async action(id,action,input,context){const screen=this.screen(id),name=text(action,'Action');const handler=screen.actions[name];if(typeof handler!=='function')throw new Error(`Unknown action ${name} on screen ${screen.id}.`);const result=await handler(input,context);qaCoverage({type:'action-pass',productId:services.security?.productId??null,brand:shell.brand?.name??null,screenId:screen.id,action:name});return result;}});
}