const text=(value,label)=>{if(typeof value!=='string'||!value.trim())throw new TypeError(`${label} is required.`);return value.trim();};
const normalizeItems=items=>{if(!Array.isArray(items)||items.length===0)throw new TypeError('Checklist items are required.');const ids=new Set();return items.map(item=>{const id=text(item?.id,'Checklist item id');if(ids.has(id))throw new Error(`Duplicate checklist item: ${id}.`);ids.add(id);return Object.freeze({id,label:text(item?.label,'Checklist item label'),required:item?.required!==false,checked:item?.checked===true,note:item?.note??null});});};
export function createChecklistService(persistence,{namespace='agro-lavoura',flags=null}={}){
 const collection=`${namespace}.checklists`;const enabled=async()=>{if(flags&&await flags.enabled('checklists.enabled')===false)throw new Error('Checklists feature is disabled.');};
 return Object.freeze({
  async create(input={}){await enabled();const id=text(input.id,'Checklist id');const payload={id,title:text(input.title,'Checklist title'),entityType:text(input.entityType,'Entity type'),entityId:text(input.entityId,'Entity id'),status:'open',items:normalizeItems(input.items),createdAt:new Date().toISOString(),completedAt:null};return persistence.putRecord(collection,id,payload,{expectedVersion:0});},
  async get(id){return persistence.getRecord(collection,text(id,'Checklist id'));},
  async list({entityType=null,entityId=null}={}){const records=await persistence.listRecords(collection);return records.filter(r=>(!entityType||r.payload.entityType===entityType)&&(!entityId||r.payload.entityId===entityId));},
  async setItem(id,itemId,{checked,note}={}){await enabled();const record=await persistence.getRecord(collection,text(id,'Checklist id'));if(!record)throw new Error('Checklist not found.');if(record.payload.status==='completed')throw new Error('Checklist is already completed.');const target=text(itemId,'Checklist item id');let found=false;const items=record.payload.items.map(item=>item.id===target?(found=true,{...item,checked:checked===true,note:note??item.note}):item);if(!found)throw new Error('Checklist item not found.');return persistence.putRecord(collection,record.id,{...record.payload,items},{expectedVersion:record.version});},
  async complete(id){await enabled();const record=await persistence.getRecord(collection,text(id,'Checklist id'));if(!record)throw new Error('Checklist not found.');const pending=record.payload.items.filter(item=>item.required&&!item.checked);if(pending.length)throw new Error(`Required checklist items are pending: ${pending.map(item=>item.id).join(', ')}.`);return persistence.putRecord(collection,record.id,{...record.payload,status:'completed',completedAt:new Date().toISOString()},{expectedVersion:record.version});}
 });
}
