const text=(v,l)=>{if(typeof v!=='string'||!v.trim())throw new TypeError(`${l} is required.`);return v.trim();};
const positive=(v,l)=>{const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new TypeError(`${l} must be positive.`);return n;};
const nonNegative=(v,l)=>{const n=Number(v??0);if(!Number.isFinite(n)||n<0)throw new TypeError(`${l} must be non-negative.`);return n;};
const coordinate=(v,l,min,max)=>{if(v==null||v==='')return null;const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw new TypeError(`${l} is invalid.`);return n;};
const idFor=(p,v)=>typeof v==='string'&&v.trim()?v.trim():(globalThis.crypto?.randomUUID?.()??`${p}-${Date.now()}-${Math.random().toString(16).slice(2)}`);
const iso=v=>new Date(v??Date.now()).toISOString(); const freeze=x=>Object.freeze(x);
export function createApplicationRecord(input={}){const areaHa=positive(input.areaHa,'Applied area');const products=(input.products??[]).map(p=>{const dose=positive(p.dosePerHa,'Dose/ha');return freeze({inputId:text(p.inputId,'Input id'),name:p.name??null,unit:p.unit??null,dosePerHa:dose,quantity:Number(p.quantity??dose*areaHa),lotNumber:p.lotNumber??null});});if(!products.length)throw new TypeError('At least one applied input is required.');return freeze({id:idFor('application',input.id),seasonId:text(input.seasonId,'Season id'),fieldId:text(input.fieldId,'Field id'),operationId:input.operationId??null,appliedAt:iso(input.appliedAt),areaHa,products:freeze(products),target:input.target??null,latitude:coordinate(input.latitude,'Latitude',-90,90),longitude:coordinate(input.longitude,'Longitude',-180,180),weather:freeze({temperatureC:input.temperatureC==null?null:Number(input.temperatureC),humidityPct:input.humidityPct==null?null:Number(input.humidityPct),windKmh:input.windKmh==null?null:Number(input.windKmh)}),operatorName:input.operatorName??null,machineName:input.machineName??null,notes:input.notes??null});}
export function createScoutingRecord(input={}){const severity=Math.max(0,Math.min(5,Number(input.severity??0)));return freeze({id:idFor('scouting',input.id),seasonId:text(input.seasonId,'Season id'),fieldId:text(input.fieldId,'Field id'),observedAt:iso(input.observedAt),kind:text(input.kind,'Occurrence type'),name:text(input.name,'Occurrence name'),severity,affectedAreaHa:input.affectedAreaHa==null?null:positive(input.affectedAreaHa,'Affected area'),latitude:coordinate(input.latitude,'Latitude',-90,90),longitude:coordinate(input.longitude,'Longitude',-180,180),notes:input.notes??null,status:input.status??'open'});}
export function createFieldGeometry(input={}){const coordinates=input.coordinates??[];if(!Array.isArray(coordinates)||coordinates.length<3)throw new TypeError('Field polygon requires at least 3 coordinates.');const points=coordinates.map(p=>{if(!Array.isArray(p)||p.length<2||!Number.isFinite(Number(p[0]))||!Number.isFinite(Number(p[1])))throw new TypeError('Invalid field coordinate.');return freeze([Number(p[0]),Number(p[1])]);});return freeze({id:String(input.fieldId),fieldId:text(input.fieldId,'Field id'),type:'Polygon',coordinates:freeze(points),source:input.source??'manual',updatedAt:iso(input.updatedAt)});}
export function inventoryPhysicalCount({sku,systemQuantity,countedQuantity,countedAt,warehouse='principal'}={}){const system=nonNegative(systemQuantity,'System quantity'),counted=nonNegative(countedQuantity,'Counted quantity');return freeze({id:idFor('count'),sku:text(sku,'Input id'),warehouse,systemQuantity:system,countedQuantity:counted,adjustmentQuantity:counted-system,countedAt:iso(countedAt)});}
export function inventoryTransfer({sku,quantity,fromWarehouse,toWarehouse,occurredAt}={}){const from=text(fromWarehouse,'Origin warehouse'),to=text(toWarehouse,'Destination warehouse');if(from===to)throw new TypeError('Warehouses must be different.');return freeze({id:idFor('transfer'),sku:text(sku,'Input id'),quantity:positive(quantity,'Transfer quantity'),fromWarehouse:from,toWarehouse:to,occurredAt:iso(occurredAt)});}
export function createHarvestRecord(input={}){const quantity=positive(input.quantity,'Harvest quantity'),areaHa=positive(input.areaHa,'Harvest area');return freeze({id:idFor('harvest',input.id),seasonId:text(input.seasonId,'Season id'),fieldId:text(input.fieldId,'Field id'),quantity,unit:text(input.unit,'Harvest unit'),areaHa,harvestedAt:iso(input.harvestedAt),yieldPerHa:quantity/areaHa,moisturePct:input.moisturePct==null?null:nonNegative(input.moisturePct,'Moisture'),impurityPct:input.impurityPct==null?null:nonNegative(input.impurityPct,'Impurity'),lossPct:input.lossPct==null?null:nonNegative(input.lossPct,'Loss'),destination:input.destination??null,loadRef:input.loadRef??null});}
export function budgetVsActual({seasons=[],entries=[]}={}){const out={};for(const season of seasons){const actual=entries.filter(e=>e.direction==='expense'&&e.metadata?.seasonId===season.id).reduce((s,e)=>s+(Number(e.amountMinor)||0),0);const budget=Number(season.budgetMinor)||0;out[season.id]=freeze({budgetMinor:budget,actualMinor:actual,varianceMinor:budget-actual,usedPct:budget>0?Math.round(actual/budget*10000)/100:null});}return freeze(out);}
export function seasonResults({seasons=[],harvestLots=[],entries=[]}={}){const budgets=budgetVsActual({seasons,entries}),out={};for(const season of seasons){const scoped=entries.filter(e=>e.metadata?.seasonId===season.id),income=scoped.filter(e=>e.direction==='income').reduce((s,e)=>s+(Number(e.amountMinor)||0),0),expense=scoped.filter(e=>e.direction==='expense').reduce((s,e)=>s+(Number(e.amountMinor)||0),0),harvest=harvestLots.filter(h=>h.seasonId===season.id),qty=harvest.reduce((s,h)=>s+Number(h.quantity||0),0),area=harvest.reduce((s,h)=>s+Number(h.areaHa||0),0);out[season.id]=freeze({incomeMinor:income,expenseMinor:expense,marginMinor:income-expense,harvestQuantity:qty,yieldPerHa:area>0?qty/area:null,budget:budgets[season.id]});}return freeze(out);}
export function managementSnapshot({fields=[],seasons=[],operations=[],harvestLots=[],entries=[],scouting=[]}={}){const results=seasonResults({seasons,harvestLots,entries});return freeze({fieldCount:fields.length,totalAreaHa:fields.reduce((s,f)=>s+Number(f.areaHa||0),0),openOperations:operations.filter(o=>['planned','in-progress'].includes(o.status)).length,completedOperations:operations.filter(o=>o.status==='completed').length,openScouting:scouting.filter(x=>x.status!=='closed').length,totalExpenseMinor:entries.filter(e=>e.direction==='expense').reduce((s,e)=>s+Number(e.amountMinor||0),0),totalIncomeMinor:entries.filter(e=>e.direction==='income').reduce((s,e)=>s+Number(e.amountMinor||0),0),seasonResults:results});}
