const freeze=v=>Object.freeze(v);const id=(p,v)=>v||globalThis.crypto?.randomUUID?.()||`${p}-${Date.now()}-${Math.random().toString(16).slice(2)}`;const text=(v,n)=>{if(!String(v??'').trim())throw new TypeError(`${n} is required`);return String(v).trim()};const pos=(v,n)=>{v=Number(v);if(!Number.isFinite(v)||v<=0)throw new TypeError(`${n} must be positive`);return v};const iso=v=>new Date(v||Date.now()).toISOString();

export function createSeasonPlan(x={}){return freeze({id:id('plan',x.id),seasonId:text(x.seasonId,'Season'),name:text(x.name,'Plan'),startsAt:iso(x.startsAt),endsAt:iso(x.endsAt),fieldIds:freeze([...(x.fieldIds||[])]),operations:freeze([...(x.operations||[])]),expectedYieldPerHa:x.expectedYieldPerHa==null?null:pos(x.expectedYieldPerHa,'Expected yield')});}
export function agriculturalCalendar({plans=[],operations=[],rainfall=[]}={}){return freeze([...plans.map(x=>({kind:'plan',at:x.startsAt,label:x.name,ref:x.id})),...operations.map(x=>({kind:'operation',at:x.scheduledAt,label:x.typeName||x.typeId,ref:x.id})),...rainfall.map(x=>({kind:'rainfall',at:x.measuredAt,label:`${x.mm} mm`,ref:x.id}))].filter(x=>x.at).sort((a,b)=>String(a.at).localeCompare(String(b.at))));}
export function createRainfall(x={}){return freeze({id:id('rain',x.id),fieldId:x.fieldId||null,farmUnitId:x.farmUnitId||null,mm:pos(x.mm,'Rainfall'),measuredAt:iso(x.measuredAt),source:x.source||'manual',notes:x.notes||null});}
export function climateSnapshot({rainfall=[],from=null,to=null}={}){const rows=rainfall.filter(x=>(!from||x.measuredAt>=from)&&(!to||x.measuredAt<=to));return freeze({mode:'offline-local',totalRainMm:rows.reduce((s,x)=>s+Number(x.mm||0),0),measurements:rows.length,externalProvider:null});}
export function createSupplier(x={}){return freeze({id:id('supplier',x.id),name:text(x.name,'Supplier'),document:x.document||null,phone:x.phone||null,email:x.email||null});}
export function createPurchaseOrder(x={}){const items=(x.items||[]).map(i=>freeze({inputId:text(i.inputId,'Input'),quantity:pos(i.quantity,'Quantity'),unitCostMinor:Math.max(0,Math.round(Number(i.unitCostMinor)||0))}));if(!items.length)throw new TypeError('Purchase order requires items');return freeze({id:id('po',x.id),supplierId:text(x.supplierId,'Supplier'),seasonId:x.seasonId||null,status:x.status||'draft',orderedAt:iso(x.orderedAt),items:freeze(items),totalMinor:items.reduce((s,i)=>s+i.quantity*i.unitCostMinor,0)});}
export function supplierPriceHistory(orders=[]){const out={};for(const o of orders)for(const i of o.items||[]){const k=`${o.supplierId}:${i.inputId}`; (out[k]??=[]).push({orderedAt:o.orderedAt,unitCostMinor:i.unitCostMinor,quantity:i.quantity});}for(const v of Object.values(out))v.sort((a,b)=>a.orderedAt.localeCompare(b.orderedAt));return freeze(out);}
export function futureInputRequirements({plannedOperations=[],stock=[]}={}){const available=new Map(stock.map(x=>[x.sku,Number(x.available??x.quantity??0)])),needed=new Map();for(const op of plannedOperations)for(const i of op.inputs||[])needed.set(i.inputId,(needed.get(i.inputId)||0)+Number(i.quantity||0));return freeze([...needed].map(([inputId,required])=>({inputId,required,available:available.get(inputId)||0,toBuy:Math.max(0,required-(available.get(inputId)||0))})));}
export function createStorageLot(x={}){return freeze({id:id('storage',x.id),seasonId:text(x.seasonId,'Season'),fieldId:x.fieldId||null,warehouse:text(x.warehouse,'Warehouse'),quantity:pos(x.quantity,'Quantity'),unit:text(x.unit,'Unit'),receivedAt:iso(x.receivedAt),quality:freeze({...x.quality}),sourceHarvestId:x.sourceHarvestId||null,status:x.status||'available'});}
export function createSale(x={}){return freeze({id:id('sale',x.id),seasonId:text(x.seasonId,'Season'),buyer:text(x.buyer,'Buyer'),quantity:pos(x.quantity,'Quantity'),unit:text(x.unit,'Unit'),unitPriceMinor:Math.max(0,Math.round(Number(x.unitPriceMinor)||0)),soldAt:iso(x.soldAt),storageLotId:x.storageLotId||null,status:x.status||'contracted'});}
export function createDelivery(x={}){return freeze({id:id('delivery',x.id),saleId:text(x.saleId,'Sale'),quantity:pos(x.quantity,'Quantity'),deliveredAt:iso(x.deliveredAt),reference:x.reference||null,status:x.status||'delivered'});}
export function compareSeasons({seasons=[],harvest=[],finance=[]}={}){return freeze(seasons.map(s=>{const h=harvest.filter(x=>x.seasonId===s.id),f=finance.filter(x=>x.metadata?.seasonId===s.id);const qty=h.reduce((a,x)=>a+Number(x.quantity||0),0),area=h.reduce((a,x)=>a+Number(x.areaHa||0),0),income=f.filter(x=>x.direction==='income').reduce((a,x)=>a+Number(x.amountMinor||0),0),expense=f.filter(x=>x.direction==='expense').reduce((a,x)=>a+Number(x.amountMinor||0),0);return freeze({seasonId:s.id,label:s.name||s.periodName,yieldPerHa:area?qty/area:null,incomeMinor:income,expenseMinor:expense,marginMinor:income-expense})}));}
export function compareFields({fields=[],harvest=[],finance=[]}={}){return freeze(fields.map(f=>{const h=harvest.filter(x=>x.fieldId===f.id),e=finance.filter(x=>x.metadata?.fieldId===f.id);const qty=h.reduce((a,x)=>a+Number(x.quantity||0),0);const expense=e.filter(x=>x.direction==='expense').reduce((a,x)=>a+Number(x.amountMinor||0),0);return freeze({fieldId:f.id,name:f.name,areaHa:f.areaHa,yieldPerHa:f.areaHa?qty/f.areaHa:null,costPerHaMinor:f.areaHa?Math.round(expense/f.areaHa):null})}));}
export function indicators({fields=[],seasons=[],harvest=[],finance=[]}={}){const sc=compareSeasons({seasons,harvest,finance});const area=fields.reduce((s,x)=>s+Number(x.areaHa||0),0),expense=finance.filter(x=>x.direction==='expense').reduce((s,x)=>s+Number(x.amountMinor||0),0),income=finance.filter(x=>x.direction==='income').reduce((s,x)=>s+Number(x.amountMinor||0),0);return freeze({managedAreaHa:area,costPerHaMinor:area?Math.round(expense/area):null,incomeMinor:income,expenseMinor:expense,marginMinor:income-expense,seasons:sc});}
export function managementReport(data={}){return freeze({generatedAt:new Date().toISOString(),indicators:indicators(data),seasonComparison:compareSeasons(data),fieldComparison:compareFields(data)});}
export function exportTable({format='csv',rows=[]}={}){const keys=[...new Set(rows.flatMap(Object.keys))];if(format==='json')return JSON.stringify(rows,null,2);if(format==='xlsx-model')return freeze({sheet:'Gestão agrícola',columns:keys,rows:rows.map(r=>keys.map(k=>r[k]??''))});const esc=v=>`"${String(v??'').replaceAll('"','""')}"`;return [keys.map(esc).join(','),...rows.map(r=>keys.map(k=>esc(r[k])).join(','))].join('\n');}
export function globalAgriculturalSearch({query,collections={}}={}){const q=String(query||'').toLocaleLowerCase('pt-BR').trim();if(!q)return freeze([]);const out=[];for(const [kind,rows] of Object.entries(collections))for(const row of rows||[]){const hay=JSON.stringify(row).toLocaleLowerCase('pt-BR');if(hay.includes(q))out.push({kind,id:row.id,label:row.name||row.description||row.reference||row.id});}return freeze(out.slice(0,100));}
export function intelligentAlerts({requirements=[],purchaseOrders=[],rainfall=[],operations=[]}={}){const out=[];for(const r of requirements)if(r.toBuy>0)out.push({severity:'warning',kind:'input-shortage',message:`Comprar ${r.toBuy} de ${r.inputId}`});const overdue=operations.filter(x=>x.status==='planned'&&x.scheduledAt&&Date.parse(x.scheduledAt)<Date.now());for(const x of overdue)out.push({severity:'warning',kind:'operation-overdue',message:`Operação atrasada: ${x.typeName||x.id}`});if(rainfall.length===0)out.push({severity:'info',kind:'rainfall-missing',message:'Sem pluviometria registrada'});return freeze(out);}
export function fieldMobileSnapshot({operations=[],scouting=[],rainfall=[]}={}){return freeze({offlineReady:true,pendingOperations:operations.filter(x=>x.status==='planned'||x.status==='in-progress'),openScouting:scouting.filter(x=>x.status!=='closed'),recentRainfall:[...rainfall].sort((a,b)=>b.measuredAt.localeCompare(a.measuredAt)).slice(0,7)});}

export function receivePurchaseOrder({order,receivedAt=new Date().toISOString(),warehouse='Principal'}={}){if(!order?.items?.length)throw new TypeError('Purchase order required');return freeze({order:freeze({...order,status:'received',receivedAt:iso(receivedAt)}),inventoryMovements:freeze(order.items.map(i=>freeze({sku:i.inputId,quantity:i.quantity,kind:'in',warehouse,reference:`purchase:${order.id}`,occurredAt:iso(receivedAt)}))) });}
export function harvestToStorage({harvest,warehouse}={}){if(!harvest?.id)throw new TypeError('Harvest required');const lot=createStorageLot({seasonId:harvest.seasonId,fieldId:harvest.fieldId,warehouse:warehouse||harvest.destination||'Produção',quantity:harvest.quantity,unit:harvest.unit,receivedAt:harvest.harvestedAt,sourceHarvestId:harvest.id,quality:{moisturePct:harvest.moisturePct??null,impurityPct:harvest.impurityPct??null}});return lot;}
export function allocateSaleFromStorage({sale,lots=[]}={}){let remaining=Number(sale?.quantity||0);if(remaining<=0)throw new TypeError('Sale quantity required');const allocations=[];for(const lot of [...lots].filter(x=>x.seasonId===sale.seasonId&&x.unit===sale.unit&&x.status!=='closed').sort((a,b)=>a.receivedAt.localeCompare(b.receivedAt))){if(remaining<=0)break;const available=Number(lot.availableQuantity??lot.quantity??0);const quantity=Math.min(available,remaining);if(quantity>0){allocations.push({storageLotId:lot.id,quantity});remaining-=quantity;}}if(remaining>0)throw new Error('Produção armazenada insuficiente para a venda');return freeze(allocations);}
export function applyStorageDelivery({lots=[],allocations=[],deliveredQuantity}={}){let remaining=pos(deliveredQuantity,'Delivered quantity'),next=lots.map(x=>({...x}));for(const a of allocations){if(remaining<=0)break;const lot=next.find(x=>x.id===a.storageLotId);if(!lot)continue;const max=Math.min(Number(a.quantity),Number(lot.availableQuantity??lot.quantity),remaining);lot.availableQuantity=Number(lot.availableQuantity??lot.quantity)-max;lot.status=lot.availableQuantity<=0?'closed':'available';remaining-=max;}if(remaining>0)throw new Error('Entrega excede alocação disponível');return freeze(next.map(freeze));}
export function saleFinancialEntry(sale,{fieldId=null}={}){return freeze({id:`sale-income:${sale.id}`,direction:'income',amountMinor:Math.round(sale.quantity*sale.unitPriceMinor),description:`Venda agrícola - ${sale.buyer}`,partyId:sale.buyer,allocation:{kind:'crop-field',id:fieldId},metadata:{seasonId:sale.seasonId,saleId:sale.id,category:'crop-sale',status:'receivable'}});}
