const finite=(value,label)=>{const parsed=Number(value);if(!Number.isFinite(parsed))throw new TypeError(`${label} must be finite.`);return parsed;};
const optionalHref=value=>typeof value==='string'&&/^https?:\/\//i.test(value)?value:null;
const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
const stable=value=>Math.round(value*1e12)/1e12;

export const SATELLITE_PROVIDERS=Object.freeze({
  sentinel2:Object.freeze({id:'sentinel2',label:'Sentinel-2 · Copernicus',endpoint:'https://stac.dataspace.copernicus.eu/v1/search',collection:'sentinel-2-l2a',attribution:'Copernicus Sentinel data',previewAssets:Object.freeze(['thumbnail','rendered_preview','preview']),redAssets:Object.freeze(['B04_10m','B04','red']),nirAssets:Object.freeze(['B08_10m','B08','nir'])}),
  landsat:Object.freeze({id:'landsat',label:'Landsat · USGS',endpoint:'https://landsatlook.usgs.gov/stac-server/search',collection:'landsat-c2l2-sr',attribution:'U.S. Geological Survey Landsat data',previewAssets:Object.freeze(['thumbnail','reduced_resolution_browse','preview']),redAssets:Object.freeze(['red']),nirAssets:Object.freeze(['nir08','nir'])})
});
function providerFor(id){const provider=SATELLITE_PROVIDERS[String(id??'')];if(!provider)throw new TypeError(`Unsupported satellite provider: ${String(id??'')}`);return provider;}
function normalizeBounds(bounds={}){const minLongitude=finite(bounds.minLongitude,'minLongitude'),minLatitude=finite(bounds.minLatitude,'minLatitude'),maxLongitude=finite(bounds.maxLongitude,'maxLongitude'),maxLatitude=finite(bounds.maxLatitude,'maxLatitude');if(minLongitude<-180||maxLongitude>180||minLatitude<-90||maxLatitude>90||minLongitude>=maxLongitude||minLatitude>=maxLatitude)throw new TypeError('Satellite bounds are invalid WGS84 coordinates.');return Object.freeze({minLongitude,minLatitude,maxLongitude,maxLatitude});}
function isoDay(value,label){const raw=String(value??'');if(!/^\d{4}-\d{2}-\d{2}$/.test(raw))throw new TypeError(`${label} is invalid.`);const date=new Date(`${raw}T00:00:00.000Z`);if(Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==raw)throw new TypeError(`${label} is invalid.`);return raw;}
function firstAsset(assets={},keys=[]){for(const key of keys){const href=optionalHref(assets?.[key]?.href);if(href)return href;}return null;}
function normalizeNdviValues(values,width,height){const w=Math.trunc(finite(width,'NDVI width')),h=Math.trunc(finite(height,'NDVI height'));if(w<=0||h<=0||!values||typeof values.length!=='number'||w*h!==values.length)throw new TypeError('NDVI dimensions do not match raster values.');const normalized=Array.from(values,value=>{const number=Number(value);return Number.isFinite(number)?stable(clamp(number,-1,1)):0;});return Object.freeze({width:w,height:h,values:Object.freeze(normalized)});}

export function buildStacSearchRequest({provider,bounds,from,to,maxCloud=100,limit=12}={}){
  const config=providerFor(provider),box=normalizeBounds(bounds),start=isoDay(from,'Satellite search start date'),end=isoDay(to,'Satellite search end date');
  if(start>end)throw new TypeError('Satellite search start date must not be after end date.');
  const cloud=clamp(finite(maxCloud,'Maximum cloud cover'),0,100),boundedLimit=clamp(Math.trunc(finite(limit,'Satellite result limit')),1,50);
  return Object.freeze({url:config.endpoint,body:Object.freeze({collections:Object.freeze([config.collection]),bbox:Object.freeze([box.minLongitude,box.minLatitude,box.maxLongitude,box.maxLatitude]),datetime:`${start}T00:00:00.000Z/${end}T23:59:59.999Z`,query:Object.freeze({'eo:cloud_cover':Object.freeze({lte:cloud})}),limit:boundedLimit,sortby:Object.freeze([{field:'datetime',direction:'desc'}])})});
}
export function normalizeStacScene(provider,item={}){
  const config=providerFor(provider);if(typeof item.id!=='string'||!item.id)throw new TypeError('STAC item id is required.');if(!Array.isArray(item.bbox)||item.bbox.length<4)throw new TypeError('STAC item bbox is required.');
  const bounds=normalizeBounds({minLongitude:item.bbox[0],minLatitude:item.bbox[1],maxLongitude:item.bbox[2],maxLatitude:item.bbox[3]});const observedAt=new Date(item.properties?.datetime??item.properties?.start_datetime??item.properties?.created??0);if(Number.isNaN(observedAt.getTime()))throw new TypeError('STAC scene datetime is invalid.');
  const cloudRaw=Number(item.properties?.['eo:cloud_cover']);const preview=firstAsset(item.assets,config.previewAssets),red=firstAsset(item.assets,config.redAssets),nir=firstAsset(item.assets,config.nirAssets);
  return Object.freeze({id:item.id,provider:config.id,providerLabel:config.label,collection:item.collection??config.collection,observedAt:observedAt.toISOString(),cloudCover:Number.isFinite(cloudRaw)?cloudRaw:null,bbox:Object.freeze([bounds.minLongitude,bounds.minLatitude,bounds.maxLongitude,bounds.maxLatitude]),assets:Object.freeze({preview,red,nir}),links:Object.freeze(Array.isArray(item.links)?item.links.filter(link=>link&&typeof link.href==='string').map(link=>Object.freeze({rel:String(link.rel??''),href:String(link.href)})):[]),attribution:config.attribution});
}
export async function searchSatelliteScenes(input={},options={}){const request=buildStacSearchRequest(input),fetcher=options.fetch??globalThis.fetch;if(typeof fetcher!=='function')throw new TypeError('Satellite search requires fetch support.');const response=await fetcher(request.url,{method:'POST',headers:{'content-type':'application/json','accept':'application/geo+json, application/json'},body:JSON.stringify(request.body)});if(!response?.ok)throw new Error(`Satellite catalog request failed (${response?.status??'network'}).`);const payload=await response.json();if(!Array.isArray(payload?.features))throw new TypeError('Satellite catalog returned an invalid FeatureCollection.');return Object.freeze(payload.features.map(item=>normalizeStacScene(input.provider,item)));}
export function calculateNdviGrid({red,nir,values,width,height}={}){if(values)return normalizeNdviValues(values,width,height);if(!red||!nir||typeof red.length!=='number'||typeof nir.length!=='number'||red.length!==nir.length)throw new TypeError('NDVI red and NIR arrays must have equal length.');const w=Math.trunc(finite(width,'NDVI width')),h=Math.trunc(finite(height,'NDVI height'));if(w<=0||h<=0||w*h!==red.length)throw new TypeError('NDVI dimensions do not match raster values.');const computed=Array.from({length:red.length},(_,index)=>{const r=Number(red[index]),n=Number(nir[index]);if(!Number.isFinite(r)||!Number.isFinite(n))return 0;const denominator=n+r;if(Math.abs(denominator)<1e-12)return 0;return stable(clamp((n-r)/denominator,-1,1));});return normalizeNdviValues(computed,w,h);}
export function summarizeNdvi(values=[]){const valid=Array.from(values,Number).filter(Number.isFinite);if(!valid.length)return Object.freeze({count:0,min:null,max:null,mean:null});const total=valid.reduce((sum,value)=>sum+value,0);return Object.freeze({count:valid.length,min:Math.min(...valid),max:Math.max(...valid),mean:stable(total/valid.length)});}
export function createSatelliteCacheEntry(input={}){const scene=input.scene;if(!scene?.id||!scene?.provider)throw new TypeError('Satellite cache requires a normalized scene.');const previewDataUrl=input.previewDataUrl==null?null:String(input.previewDataUrl);if(previewDataUrl&&!/^data:image\/(?:png|jpe?g|webp);base64,/i.test(previewDataUrl))throw new TypeError('Satellite preview must be an image data URL.');if(previewDataUrl&&previewDataUrl.length>7_000_000)throw new RangeError('Satellite preview exceeds the local cache limit.');const ndvi=input.ndvi?.values?Object.freeze({...normalizeNdviValues(input.ndvi.values,input.ndvi.width,input.ndvi.height),summary:summarizeNdvi(input.ndvi.values)}):null;const cachedAt=new Date(input.cachedAt??Date.now());if(Number.isNaN(cachedAt.getTime()))throw new TypeError('Satellite cachedAt is invalid.');return Object.freeze({id:`${scene.provider}:${scene.id}`,scene:Object.freeze(structuredClone(scene)),previewDataUrl,ndvi,cachedAt:cachedAt.toISOString()});}
