import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createBrowserPersistence,createBrowserRecovery} from '../shared/packages/vertical-persistence/src/browser.js';
import {createAgroLavouraPresentation} from '../src/presentation.js';
import {createRpcBackend} from '../runtime/backend.mjs';
import './styles.css';

async function resolveBackend(){if(globalThis.artisys)return globalThis.artisys;const persistence=createBrowserPersistence({productId:'agro-lavoura'});const recovery=createBrowserRecovery(persistence,{productId:'agro-lavoura'});const presentation=createAgroLavouraPresentation({persistence,recovery});return createRpcBackend({presentation});}
const toRows=(data)=>{const candidate=Array.isArray(data)?data:data?.rows??data?.records??Object.values(data??{}).find(Array.isArray)??[];return candidate.map(v=>v?.payload??v);};
const text=(v)=>v==null?'—':typeof v==='object'?JSON.stringify(v):String(v);
function Auth({backend,onAuth}){const [hasUsers,setHasUsers]=useState(true),[username,setUsername]=useState('admin'),[password,setPassword]=useState(''),[error,setError]=useState('');useEffect(()=>{backend.authState().then(v=>setHasUsers(v.hasUsers));},[backend]);async function submit(e){e.preventDefault();setError('');try{if(!hasUsers)await backend.bootstrap({username,password});const login=await backend.login({username,password});onAuth({sessionId:login.session.id,token:login.token});}catch(err){setError(err.message);}}return <main className="auth"><form onSubmit={submit} className="panel"><h1>ArtiSys Lavoura</h1><p>{hasUsers?'Entre para continuar':'Crie o administrador local'}</p><label>Usuário<input data-testid="username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Senha<input data-testid="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8}/></label>{error&&<div className="error">{error}</div>}<button data-testid="auth-submit">{hasUsers?'Entrar':'Criar administrador'}</button></form></main>}
function ActionPanel({screen,selected,onRun}){const [chosen,setChosen]=useState(null),[raw,setRaw]=useState('{}'),[error,setError]=useState('');const defs=screen?.actionDefinitions??{};useEffect(()=>{setChosen(null);setRaw('{}');},[screen?.id]);const start=(name)=>{setChosen(name);const def=defs[name];const base={};if(def?.requiresSelection&&selected?.id)base.id=selected.id;setRaw(JSON.stringify(base,null,2));};async function run(){try{setError('');const input=JSON.parse(raw||'{}');await onRun(chosen,input);setChosen(null);setRaw('{}');}catch(err){setError(err.message);}}return <aside className="actions"><h3>Ações</h3><div className="action-buttons">{Object.entries(defs).map(([name,def])=><button key={name} onClick={()=>start(name)}>{def.label??name}</button>)}</div>{chosen&&<div className="action-editor"><strong>{defs[chosen]?.label??chosen}</strong><label>JSON de entrada<textarea data-testid="action-json" value={raw} onChange={e=>setRaw(e.target.value)} rows={8}/></label><button data-testid="action-run" onClick={run}>Executar</button></div>}{error&&<div className="error">{error}</div>}</aside>}
function Screen({screen,data,onSelect,selected}){const rows=toRows(data);if(data?.cards)return <section className="cards">{Object.entries(data.cards).map(([k,v])=><article key={k}><small>{k}</small><strong>{text(v)}</strong></article>)}</section>;if(!rows.length)return <section className="empty">Nenhum registro. Use as ações para cadastrar.</section>;const columns=[...new Set(rows.flatMap(row=>Object.keys(row??{})))].filter(k=>!['metadata'].includes(k)).slice(0,9);return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={row.id??i} data-selected={selected===row} onClick={()=>onSelect(row)}>{columns.map(c=><td key={c}>{text(row[c])}</td>)}</tr>)}</tbody></table></div>}
function App(){const [backend,setBackend]=useState(null),[auth,setAuth]=useState(()=>{try{return JSON.parse(localStorage.getItem('artisys.auth')||'null')}catch{return null}}),[meta,setMeta]=useState(null),[screenId,setScreenId]=useState(null),[data,setData]=useState(null),[selected,setSelected]=useState(null),[error,setError]=useState('');useEffect(()=>{resolveBackend().then(setBackend);},[]);useEffect(()=>{if(auth)localStorage.setItem('artisys.auth',JSON.stringify(auth));else localStorage.removeItem('artisys.auth');},[auth]);useEffect(()=>{if(!backend||!auth)return;backend.validate(auth).then(()=>backend.describe()).then(m=>{setMeta(m);setScreenId(v=>v??m.navigation[0]?.id);}).catch(()=>setAuth(null));},[backend,auth]);async function load(id=screenId){if(!backend||!auth||!id)return;setError('');try{setData(await backend.load({screenId:id,auth,context:{}}));setSelected(null);}catch(err){setError(err.message);}}useEffect(()=>{void load();},[screenId,meta]);if(!backend)return <div className="loading">Carregando…</div>;if(!auth)return <Auth backend={backend} onAuth={setAuth}/>;if(!meta)return <div className="loading">Abrindo produto…</div>;const descriptor=meta.screens.find(s=>s.id===screenId);return <div className="app"><header><div><b>{meta.brand?.productName??meta.brand?.name}</b><small>standalone · local-first</small></div><button onClick={async()=>{try{await backend.logout(auth);}finally{setAuth(null);}}}>Sair</button></header><div className="layout"><nav>{meta.navigation.map(item=><button data-testid={`nav-${item.id}`} className={item.id===screenId?'active':''} key={item.id} onClick={()=>setScreenId(item.id)}>{item.label??item.id}</button>)}</nav><main><div className="screen-head"><h2>{descriptor?.title??screenId}</h2><button onClick={()=>load()}>Atualizar</button></div>{error&&<div className="error">{error}</div>}<Screen screen={descriptor} data={data} selected={selected} onSelect={setSelected}/></main><ActionPanel screen={descriptor} selected={selected} onRun={async(action,input)=>{await backend.action({screenId,action,input,auth,context:{}});await load();}}/></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
